# Generated by Django 5.2.1 on 2025-05-14 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('aventure', 'Aventure'), ('rpg', 'RPG'), ('strategie', 'Stratégie'), ('simulation', 'Simulation'), ('sport', 'Sport'), ('course', 'Course'), ('combat', 'Combat'), ('plateforme', 'Plateforme'), ('puzzle', 'Puzzle')], max_length=20)),
                ('ambiance', models.CharField(choices=[('heroic', 'Héroïque'), ('dark', 'Sombre'), ('comedy', 'Comédie'), ('mystery', 'Mystère'), ('horror', 'Horreur'), ('fantasy', 'Fantaisie'), ('scifi', 'Science-Fiction'), ('realistic', 'Réaliste')], max_length=20)),
                ('description', models.TextField()),
                ('gameplay', models.TextField()),
                ('story', models.TextField()),
                ('characters', models.TextField()),
                ('environment', models.TextField()),
                ('concept_art', models.ImageField(blank=True, null=True, upload_to='concept_art/')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
